changelog:
  exclude:
    labels:
      - ignore-for-release
  categories:
    - title: Breaking Changes 🛠
      labels:
        - breaking-change
    - title: Exciting New Features 🎉
      labels:
        - enhancement
    - title: Other Changes
      labels:
        - "*"
      exclude:
        labels:
          - dependencies
    - title: Dependencies
      labels:
        - dependencies
